# Generated by Django 3.0.1 on 2021-01-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.TextField(default='its cool'),
        ),
    ]
