# Generated by Django 3.0.1 on 2021-01-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
